title: GitHub Foray
author: Be Peace
email: private
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Site description - will appear in document head meta (for Google search results) and in feed.xml site description.

# social links
twitter_username: private
github_username:  BePeace

show_excerpts: true # set to false to remove excerpts on the homepage
